# Google Cloud Build configuration for HitchBuddy deployment
steps:
  # Install dependencies with dev dependencies for build tools
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--include=dev']
    env:
      - 'NODE_ENV=production'

  # Build the application using our optimized build script
  - name: 'node:20'
    entrypoint: 'node'
    args: ['deploy-build.js']
    env:
      - 'NODE_ENV=production'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/hitchbuddy:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/hitchbuddy:latest',
      '.'
    ]

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hitchbuddy:$BUILD_ID']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'hitchbuddy',
      '--image', 'gcr.io/$PROJECT_ID/hitchbuddy:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '100',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hitchbuddy:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/hitchbuddy:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY