apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hitchbuddy
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/hitchbuddy:latest
        name: hitchbuddy
        ports:
        - containerPort: 80
          name: http1
        env:
        - name: NODE_ENV
          value: "production"
        - name: IS_PRODUCTION_DEPLOYMENT
          value: "true"
        - name: PORT
          value: "80"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true