# fly.toml file generated for hitchbuddy

app = "hitchbuddy"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[checks]
  [checks.api_health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/auth/me"
    port = 8080
    timeout = "5s"
    type = "http"