[build]
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/auth/me"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "3000" }