services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: development
      - key: FORCE_DEV_MODE
        value: 'true'
      - key: PORT
        value: '10000'
    healthCheckPath: /health
    autoDeploy: false