services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: node deploy-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health
    autoDeploy: false