services:
  - type: web
    name: hitchbuddy-node
    env: node
    region: frankfurt
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node static-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false