services:
  - type: web
    name: hitchbuddy-app
    env: node
    buildCommand: cp package.json.simple package.json && echo "Build complete - standalone server ready"
    startCommand: node deploy-server.cjs
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false