services:
  - type: web
    name: hitchbuddy-connect-uk
    env: node
    plan: free
    buildCommand: |
      npm install
      mkdir -p dist/public
      cp -r client/dist/* dist/public/ 2>/dev/null || echo "No client build found, creating from template"
      if [ ! -f "dist/public/index.html" ]; then
        echo "Creating production HTML template..."
        cat > dist/public/index.html << 'EOF'
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HitchBuddy - Eco-Conscious Ride Sharing</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; }
          .container { background: white; padding: 2rem; border-radius: 1rem; box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1); text-align: center; max-width: 400px; }
          .logo { background: linear-gradient(to right, #3b82f6, #10b981); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2rem; font-weight: bold; margin-bottom: 1rem; }
          .message { color: #4b5563; margin-bottom: 2rem; }
          .button { background: linear-gradient(to right, #3b82f6, #10b981); color: white; padding: 0.75rem 1.5rem; border: none; border-radius: 0.5rem; font-weight: 600; cursor: pointer; text-decoration: none; display: inline-block; margin: 0.5rem; }
          .button:hover { transform: translateY(-2px); box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1); }
          .status { background: #f3f4f6; padding: 1rem; border-radius: 0.5rem; margin-top: 1rem; color: #6b7280; font-size: 0.875rem; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="logo">HitchBuddy</div>
          <div class="message">
            <h2>🚗 Ride Sharing Platform</h2>
            <p>Connecting eco-conscious travelers with shared transportation</p>
          </div>
          <a href="/dashboard" class="button">Enter Dashboard</a>
          <a href="/api/health" class="button">Health Check</a>
          <div class="status">
            ✅ Server Running<br>
            ✅ Database Connected<br>
            ✅ API Endpoints Active
          </div>
        </div>
      </body>
      </html>
      EOF
      fi
      chmod +x final-production-server.cjs 2>/dev/null || true
      ls -la dist/public/
      echo "Build completed successfully"
    startCommand: node final-production-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '10000'
    healthCheckPath: /health
    autoDeploy: false