services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: npm install && npm install -g tsx ts-node && chmod +x build-client.sh
    startCommand: node deploy-server.cjs
    envVars:
      - key: NODE_ENV
        value: development
      - key: FORCE_DEV_MODE
        value: 'true'
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health
    autoDeploy: false