services:
  - type: web
    name: hitchbuddy-node
    env: node
    buildCommand: npm ci --include=dev && npx vite build && cp static-server.cjs ./
    startCommand: node static-server.cjs
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false