services:
  - type: web
    name: hitchbuddy-app
    env: node
    buildCommand: ./deploy-build.sh
    startCommand: node deploy-server.cjs
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false