services:
  - type: web
    name: hitchbuddy
    env: node
    region: oregon
    plan: free
    buildCommand: bash deploy-build.sh
    startCommand: node hitchbuddy-real.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health