services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: |
      npm install
      mkdir -p dist/public
      chmod +x final-production-server.cjs 2>/dev/null || true
      echo "Build completed successfully"
    startCommand: node final-production-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '10000'
    healthCheckPath: /health
    autoDeploy: false