services:
  - type: web
    name: hitchbuddy
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    staticPublishPath: ./client/dist
