services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: echo "No build needed - using existing files"
    startCommand: node deploy-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health
    autoDeploy: false