services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: npm install && rm -rf client/dist
    startCommand: node deploy-server.cjs
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health
    autoDeploy: false