services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: |
      npm install
      chmod +x build-client.sh
      chmod +x start-production.sh
      chmod +x deploy-server.cjs
    startCommand: bash start-production.sh
    envVars:
      - key: NODE_ENV
        value: development
      - key: FORCE_DEV_MODE
        value: 'true'
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health
    autoDeploy: false