services:
  - type: web
    name: hitchbuddy-node
    env: node
    buildCommand: cp deploy-server.cjs ./
    startCommand: node deploy-server.cjs
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false