services:
  - type: web
    name: hitchbuddy
    env: node
    region: oregon
    plan: free
    buildCommand: echo "No build required - using dependency-free server"
    startCommand: node server-fullstack.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health