services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: |
      npm install
      echo "Using existing compiled build - no build process needed"
    startCommand: node final-production-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_DEV_MODE
        value: 'false'
      - key: PORT
        fromService:
          type: web
          name: hitchbuddy
          property: port
    healthCheckPath: /health
    autoDeploy: false