services:
  - type: web
    name: hitchbuddy
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hitchbuddy-db
          property: connectionString
    autoDeploy: false

databases:
  - name: hitchbuddy-db
    databaseName: hitchbuddy
    plan: starter