services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node deploy-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_DEV_MODE
        value: 'false'
      - key: PORT
        value: '10000'
    healthCheckPath: /health
    autoDeploy: false