services:
  - type: web
    name: hitchbuddy
    env: node
    plan: starter
    buildCommand: node build.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
    autoDeploy: false