services:
  - type: web
    name: hitchbuddy
    env: node
    region: frankfurt  # EU region closest to UK
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node static-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false