services:
  - type: web
    name: hitchbuddy
    env: docker
    region: frankfurt  # EU region closest to UK
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hitchbuddy-db
          property: connectionString

databases:
  - name: hitchbuddy-db
    region: frankfurt  # EU region
    plan: free