services:
  - type: web
    name: hitchbuddy
    env: node
    plan: free
    buildCommand: |
      npm install
      mkdir -p dist/public
      ls -la
      echo "Build completed - files available"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '10000'
    healthCheckPath: /health
    autoDeploy: false