#!/bin/bash
# Quick setup script for Vercel environment variables

echo "🔧 Vercel Environment Variables Setup"
echo "===================================="
echo ""
echo "Follow these steps in your Vercel dashboard:"
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click on your Hitchbuddy project"
echo "3. Go to Settings → Environment Variables"
echo ""
echo "4. Add these variables:"
echo ""
echo "   Variable 1:"
echo "   Name: DATABASE_URL"
echo "   Value: [Your Supabase connection string]"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Variable 2:"
echo "   Name: NODE_ENV"
echo "   Value: production"
echo "   Environments: Production"
echo ""
echo "5. Save and redeploy if prompted"
echo ""
echo "🚀 After setup, your app will be live at:"
echo "   https://your-project-name.vercel.app"