// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgcplxhabpujgcwglrfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnY3BseGhhYnB1amdjd2dscmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NDM5NzUsImV4cCI6MjA2NjExOTk3NX0.T2Ccl3H4NaD00VWu9gmhwIVtWHZs3zYegFzVFoZ7mgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);